# Generated by Django 4.1.7 on 2023-12-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter full name', max_length=300, null=True, verbose_name='Full Name')),
                ('telegram_id', models.CharField(help_text='Enter telegram id', max_length=100, unique=True, verbose_name='Telegram ID')),
                ('language', models.CharField(default='uz', help_text='Enter language', max_length=4, verbose_name='Language')),
                ('phone', models.CharField(blank=True, help_text='Enter phone number', max_length=20, null=True, verbose_name='Phone number')),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot User',
                'verbose_name_plural': 'Bot Users',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter category', max_length=150, verbose_name='Category')),
                ('name_uz', models.CharField(help_text='Enter category', max_length=150, null=True, verbose_name='Category')),
                ('name_ru', models.CharField(help_text='Enter category', max_length=150, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.botusermodel', to_field='telegram_id', verbose_name='Bot User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='TelegramChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='Enter channel id', max_length=150, unique=True, verbose_name='Channel ID')),
                ('channel_name', models.CharField(blank=True, help_text='Enter channel name', max_length=300, null=True, verbose_name='Channel Name')),
                ('channel_members_count', models.CharField(blank=True, help_text='Enter channel members count', max_length=200, null=True, verbose_name='Channel Memers Count')),
            ],
            options={
                'verbose_name': 'Telegram Channel',
                'verbose_name_plural': 'Telegram Channels',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter subcategory', max_length=150, verbose_name='Subcategory')),
                ('name_uz', models.CharField(help_text='Enter subcategory', max_length=150, null=True, verbose_name='Subcategory')),
                ('name_ru', models.CharField(help_text='Enter subcategory', max_length=150, null=True, verbose_name='Subcategory')),
                ('category', models.ForeignKey(blank=True, help_text='Choose category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='app.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
                'db_table': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter product name', max_length=150, null=True, verbose_name='Product')),
                ('name_uz', models.CharField(blank=True, help_text='Enter product name', max_length=150, null=True, verbose_name='Product')),
                ('name_ru', models.CharField(blank=True, help_text='Enter product name', max_length=150, null=True, verbose_name='Product')),
                ('image', models.ImageField(blank=True, help_text='Upload image', null=True, upload_to='my-images', verbose_name='Image')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_uz', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_ru', models.TextField(blank=True, null=True, verbose_name='About')),
                ('price', models.IntegerField(default=0, help_text='Enter price', verbose_name='Price')),
                ('discount', models.IntegerField(default=0, help_text='Enter discount', verbose_name='Discount')),
                ('category', models.ForeignKey(help_text='Choose category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category', verbose_name='Category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.subcategory', verbose_name='Subcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
                'db_table': 'OrderItem',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.botusermodel', to_field='telegram_id', verbose_name='Bot User')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'Location',
            },
        ),
    ]
