# Generated by Django 4.1.7 on 2024-06-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_7food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Full name')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Phone')),
                ('product', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Product')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity')),
                ('narxi', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prepared', models.BooleanField(default=False, help_text='Agar buyurtma tayyorlangan bo`lsa chekboxni bosing !!!')),
                ('delivered', models.BooleanField(default=False, verbose_name='Delivered')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'Order_7food',
            },
        ),
    ]
