# Generated by Django 4.1.7 on 2024-06-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_7food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_7food',
            name='location',
        ),
        migrations.RemoveField(
            model_name='order_7food',
            name='quantity',
        ),
    ]
