# Generated by Django 4.1.7 on 2024-06-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_order_7food_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Order Table',
                'verbose_name_plural': 'Order Tables',
                'db_table': 'OrderTable',
            },
        ),
        migrations.CreateModel(
            name='OrderTableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('order_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.ordertable', verbose_name='Order Table')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Table Item',
                'verbose_name_plural': 'Order Table Items',
                'db_table': 'OrderTableItem',
            },
        ),
        migrations.AddField(
            model_name='ordertable',
            name='products',
            field=models.ManyToManyField(related_name='order_tables', through='app.OrderTableItem', to='app.product', verbose_name='Products'),
        ),
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Product')),
            ],
        ),
    ]
