# Generated by Django 4.1.7 on 2024-06-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ordertable_ordertableitem_ordertable_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='name',
            field=models.CharField(default='foydalanuvchi', max_length=300, verbose_name='Name'),
        ),
    ]
