# Generated by Django 4.1.7 on 2024-06-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ordertable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxminiy_vaqt',
            field=models.IntegerField(blank=True, default=2, help_text='Tayyorlash uchun ketadigan  taxminiy vaqtni Kiriting !!', null=True),
        ),
    ]
