# Generated by Django 4.1.7 on 2024-06-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_saboyfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusermodel',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
