# Generated by Django 4.1.7 on 2024-06-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_botusermodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='status',
            field=models.BooleanField(default=False, help_text='Tayyorlanga bo`lsa statusni belgilab keting !!!', verbose_name='Status'),
        ),
    ]
