# Generated by Django 4.1.7 on 2024-06-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_7food_taxminiy_vaqt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_7food',
            name='taxminiy_vaqt',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Taxminiy Vaq'),
        ),
        migrations.AlterField(
            model_name='order_saboyfood',
            name='taxminiy_vaqt',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Taxminiy Vaq'),
        ),
    ]
